# Generated by Django 3.1 on 2024-11-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('carrinho_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'carrinho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarrinhoProduto',
            fields=[
                ('id_c_p', models.AutoField(primary_key=True, serialize=False)),
                ('venda_id', models.IntegerField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrinho_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nif', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=50, null=True)),
                ('ntelefone', models.DecimalField(decimal_places=0, max_digits=9)),
                ('morada', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logista',
            fields=[
                ('nif', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=50, null=True)),
                ('ntelefone', models.DecimalField(decimal_places=0, max_digits=9)),
                ('morada', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'logista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogistaProduto',
            fields=[
                ('addp_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'logista_produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('venda_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venda',
                'managed': False,
            },
        ),
    ]
