# Generated by Django 4.2.16 on 2024-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projpsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='produtos_images/')),
            ],
            options={
                'db_table': 'produtoimagem',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logista',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='utilizador',
            options={'managed': False},
        ),
    ]
