# Generated by Django 4.2.16 on 2024-12-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpsi', '0002_produtoimagem_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='logista',
            table='logista',
        ),
        migrations.AlterModelTable(
            name='utilizador',
            table='utilizador',
        ),
    ]
