# Generated by Django 4.2.16 on 2024-12-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projpsi', '0003_alter_cliente_table_alter_logista_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lojista',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lojista', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lojista',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Logista',
        ),
    ]
