# Generated by Django 5.1.4 on 2024-12-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projpsi', '0004_lojista_delete_logista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={},
        ),
    ]
