--USE Proj_PSI;
--GO

--CREATE SCHEMA IF NOT EXISTS ;

DROP TABLE CARRINHO_PRODUTO;

DROP TABLE FAVORITO;
DROP TABLE VENDA;
DROP TABLE PRODUTOIMAGEM;
DROP TABLE PRODUTO;
--DROP TABLE CARRINHO;
--DROP TABLE CLIENTE;
DROP TABLE LOGISTA;
--DROP TABLE UTILIZADOR;


CREATE TABLE IF NOT EXISTS UTILIZADOR(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    nif NUMERIC(9, 0) NULL,
    ntelefone NUMERIC(9, 0) NULL,
    morada VARCHAR(50) NULL,
    password VARCHAR(128) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    date_joined TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE
);


CREATE TABLE IF NOT EXISTS CLIENTE (
    user_id INTEGER NOT NULL UNIQUE REFERENCES UTILIZADOR(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS LOJISTA (
    user_id INTEGER NOT NULL UNIQUE REFERENCES UTILIZADOR(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id)
);


CREATE TABLE IF NOT EXISTS PRODUTO(
	id			SERIAL PRIMARY KEY, 
	ID_LOJISTA 	INTEGER NOT NULL,
	Stock		INTEGER NOT NULL,
	Nome		VARCHAR NOT NULL,
	Preco		NUMERIC(10,2) NOT NULL,
	Descricao	VARCHAR, 
	Categoria   VARCHAR CHECK (Categoria IN ('computador fixo', 'computador portátil', 'periférico', 'acessório')),

	FOREIGN KEY (ID_LOJISTA) REFERENCES LOJISTA(user_id)
);


CREATE TABLE IF NOT EXISTS PRODUTOIMAGEM(
	id			SERIAL PRIMARY KEY, 
	Produto_id		INTEGER NOT NULL REFERENCES Produto(id) ON DELETE CASCADE,
    Imagem 		VARCHAR NOT NULL
);


CREATE TABLE IF NOT EXISTS CARRINHO(
	id	SERIAL PRIMARY KEY,
	ID_CLIENTE	INTEGER NOT NULL,
	TOTAL		NUMERIC(10,2),

	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(user_id)
);



CREATE TABLE IF NOT EXISTS FAVORITO(
	id		SERIAL PRIMARY KEY,
	ID_CLIENTE	INTEGER NOT NULL,
	PRODUTO_ID	INTEGER NOT NULL,

	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(user_id),
	FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(id)
);


CREATE TABLE IF NOT EXISTS VENDA(
	id	SERIAL PRIMARY KEY,
	CARRINHO_ID	INTEGER,
	DATA_VENDA	DATE, 

	FOREIGN KEY (CARRINHO_ID) REFERENCES CARRINHO(id)
);

CREATE TABLE IF NOT EXISTS CARRINHO_PRODUTO(
	ID_C_P		SERIAL PRIMARY KEY, 
	CARRINHO_ID	INTEGER NOT NULL,
	VENDA_ID	INTEGER,
	PRODUTO_ID	INTEGER NOT NULL,
	QUANTIDADE	INTEGER NOT NULL,

	FOREIGN KEY (CARRINHO_ID) REFERENCES CARRINHO(id),
	FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(id), 
	FOREIGN KEY (VENDA_ID) REFERENCES VENDA(id)
);

