--USE Proj_PSI;
--GO

--CREATE SCHEMA IF NOT EXISTS ECOMMERCE;

--DROP TABLE ECOMMERCE.CARRINHO_PRODUTO_VENDA;

--DROP TABLE ECOMMERCE.FAVORITO;
--DROP TABLE ECOMMERCE.LOGISTA_PRODUTO;
--DROP TABLE ECOMMERCE.VENDA;
--DROP TABLE ECOMMERCE.CARRINHO;
--DROP TABLE ECOMMERCE.CLIENTE;
--DROP TABLE ECOMMERCE.LOGISTA;
--DROP TABLE ECOMMERCE.PRODUTO;




CREATE TABLE IF NOT EXISTS ECOMMERCE.CLIENTE(
	NIF			NUMERIC(9,0) PRIMARY KEY,
	Nome		varchar NOT NULL, 
	Mail		varchar NOT NULL UNIQUE,
	Pass		varchar, 
	NTelefone	NUMERIC(9,0) NOT NULL,
	Morada		varchar NOT NULL 
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.LOGISTA(
	NIF			NUMERIC(9,0) PRIMARY KEY,
	Nome		varchar NOT NULL, 
	Mail		varchar NOT NULL,
	Pass		varchar, 
	NTelefone	NUMERIC(9,0) NOT NULL,
	Morada		varchar
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.PRODUTO(
	IDPRODUTO	SERIAL PRIMARY KEY, 
	Stock		DECIMAL NOT NULL,
	Nome		VARCHAR NOT NULL,
	Preco		NUMERIC(10,2) NOT NULL,
	Descricao	VARCHAR, 
	Categoria	VARCHAR
);



CREATE TABLE IF NOT EXISTS ECOMMERCE.CARRINHO(
	CARRINHO_ID	SERIAL PRIMARY KEY,
	NIF_CLIENTE	NUMERIC(9,0) NOT NULL,
	TOTAL		NUMERIC(10,2),

	FOREIGN KEY (NIF_CLIENTE) REFERENCES ECOMMERCE.CLIENTE(NIF)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.CARRINHO_PRODUTO_VENDA(
	ID_C_P		SERIAL PRIMARY KEY, 
	CARRINHO_ID	INTEGER,
	VENDA_ID	INTEGER,
	PRODUTO_ID	INTEGER,
	QUANTIDADE	DECIMAL,

	FOREIGN KEY (CARRINHO_ID) REFERENCES ECOMMERCE.CARRINHO(CARRINHO_ID),
	FOREIGN KEY (PRODUTO_ID) REFERENCES ECOMMERCE.PRODUTO(IDPRODUTO)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.FAVORITO(
	FAV_ID		SERIAL PRIMARY KEY,
	NIF_CLIENTE	NUMERIC(9,0) NOT NULL,
	PRODUTO_ID	INTEGER NOT NULL,

	FOREIGN KEY (NIF_CLIENTE) REFERENCES ECOMMERCE.CLIENTE(NIF),
	FOREIGN KEY (PRODUTO_ID) REFERENCES ECOMMERCE.PRODUTO(IDPRODUTO)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.LOGISTA_PRODUTO(
	ADDP_ID		SERIAL PRIMARY KEY,
	LOGISTA_NIF	NUMERIC(9,0) NOT NULL,
	PRODUTO_ID	INTEGER NOT NULL,

	FOREIGN KEY (LOGISTA_NIF) REFERENCES ECOMMERCE.LOGISTA(NIF),
	FOREIGN KEY (PRODUTO_ID) REFERENCES ECOMMERCE.PRODUTO(IDPRODUTO)
);

CREATE TABLE IF NOT EXISTS ECOMMERCE.VENDA(
	VENDA_ID	SERIAL PRIMARY KEY,
	CARRINHO_ID	INTEGER,
	NIF_CLIENTE	NUMERIC(9,0),
	DATA_VENDA	DATE, 

	FOREIGN KEY (CARRINHO_ID) REFERENCES ECOMMERCE.CARRINHO(CARRINHO_ID),
	FOREIGN KEY (NIF_CLIENTE) REFERENCES ECOMMERCE.CLIENTE(NIF)
);


--------------------------------------------------------------------------------------------
--------------------------- ADICIONAR CONTEÚDOS INICIAIS------------------------------------
--------------------------------------------------------------------------------------------


--INSERT INTO ECOMMERCE.CLIENT
--VALUES
--('123456789', 'Maria do Mar', 'mariadomar@mail.com', '123Oliveira4', '987654321', 'Rua do Oceano n14'),
--('134677985', 'Rodrigo Alteres', 'stronrodrigo@mail.pt', 'homemforte', '989898989', 'Rua do ginasio n5'),
--('242424242', 'Mariana Pinheiro', 'marianapinheiro@ua.pt', 'palavrapass', '916562734', 'a minha rua n27');


--INSERT INTO ECOMMERCE.LOGISTA
--VALUES
--('454545454', 'loja fixe', 'fixe@store.pt', 'password', '888888889', 'rua bacana n45'),
--('124578986', 'Loja do Mestre André', 'mestreandre@store.pt', 'passdaloja', '326598147', 'Rua da loja n12');


--INSERT INTO ECOMMERCE.PRODUTO(Stock, Nome, Preco, Descricao, Categoria)
--VALUES
--('3', 'OLAOLA', '14', 'JVNÇDFJNV', 'JKBVJBJ'),
--('5', 'PIUPIU', '20', 'TICOTICO', 'JNJFDJJJ'),
--('9', 'BACALHAU', '50', 'ZAZA', 'ANONIO');