----------------------------------DROP DROP----------------------------------
DROP PROCEDURE ecommerce.logistaadicionaproduto(numeric,character varying,numeric,numeric,character varying,character varying); 
DROP PROCEDURE ecommerce.clientefavorita(numeric,numeric);
--DROP PROCEDURE ECOMMERCE.ClientAddProductCart(numeric,numeric, numeric,numeric);

CREATE OR REPLACE PROCEDURE ECOMMERCE.LogistaAdicionaProduto(O_NifLogista NUMERIC(9,0), O_NomeProduto VARCHAR, O_Stock NUMERIC, O_Preco NUMERIC(10,2), O_descricao VARCHAR, O_categoria VARCHAR)
LANGUAGE plpgsql
AS $$
	BEGIN	
		INSERT INTO ECOMMERCE.PRODUTO(Stock, Nome, Preco, Descricao, Categoria)
		VALUES (O_Stock, O_NomeProduto, O_Preco, O_descricao, O_categoria);
		
		INSERT INTO ECOMMERCE.LOGISTA_PRODUTO(LOGISTA_NIF, PRODUTO_ID)
		VALUES (O_NifLogista, O_CODIGO);
		
	END;
$$;



CREATE OR REPLACE PROCEDURE ECOMMERCE.ClienteFavorita(O_Nif_cliente NUMERIC(9,0), O_PRODUTO_ID NUMERIC)
LANGUAGE plpgsql
AS $$
	BEGIN
		INSERT INTO ECOMMERCE.FAVORITO(NIF_CLIENTE, PRODUTO_ID)
		VALUES (O_Nif_cliente, O_PRODUTO_ID);
	END;
$$;



CREATE OR REPLACE PROCEDURE ECOMMERCE.NewCart(O_USER_NIF NUMERIC(9,0))
LANGUAGE plpgsql
AS $$
	DECLARE
		O_PRECO NUMERIC = 0.00;
	BEGIN
		INSERT INTO ECOMMERCE.CARRINHO(NIF_CLIENTE, TOTAL)
		VALUES(O_USER_NIF, O_PRECO);
	END;
$$;



--CREATE OR REPLACE PROCEDURE ECOMMERCE.ClientAdicionaProdutoCarrinho(O_Nif_cliente NUMERIC(9,0), O_PRODUCT_ID NUMERIC, O_CART_ID NUMERIC, O_QUANTITY NUMERIC)
--LANGUAGE plpgsql
--AS $$
--	DECLARE
--		--CARTID NUMERIC := RAND()*1000;
		--CARTPRODUCTID NUMERIC := RAND()*1000;
--	BEGIN
--		INSERT INTO ECOMMERCE.CARRINHO_PRODUCT_VENDA(ID_C_P, CART_ID, PRODUCT_ID, QUANTITY)
--		VALUES (CARTPRODUCTID, O_CART_ID, O_PRODUCT_ID, O_QUANTITY);
--	END;
--$$;



-- GERAR UM CARRINHO VAZIO EX:QUANDO SE CRIA UM NOVO UTILIZADOR
-- FAZER UM UPDATE AUTOMÁTICO DO TOTAL DO CARRINHO

-- ADICIONAR VALORES INICIAIS