CREATE OR REPLACE PROCEDURE ECOMMERCE.LogistaAdicionaProduto(O_NifLogista NUMERIC(9,0), O_NomeProduto VARCHAR, O_Stock NUMERIC, O_Preco NUMERIC(10,2), O_Descricao VARCHAR, O_categoria VARCHAR)
LANGUAGE plpgsql
AS $$
	--BEGIN
	DECLARE 
		O_CODIGO NUMERIC :=RAND()*1000;
		O_CODIGO2 NUMERIC:=RAND()*1000;
		--SET O_CODIGO=RAND()*1000;
	BEGIN	
		INSERT INTO ECOMMERCE.PRODUTO(IDPRODUTO, Stock, Nome, Preco, Descricao, Categoria)
		VALUES (O_CODIGO, O_Stock, O_NomeProduto, O_Preco, O_Descricao, O_categoria);
		--DECLARE O_CODIGO2 INT;
		--SET O_CODIGO2=RAND()*1000;
		INSERT INTO ECOMMERCE.LOGISTA_PRODUTO(ADICIONA_P_ID, LOGISTA_NIF, PRODUTO_ID)
		VALUES (O_CODIGO2, O_NifLogista, O_CODIGO);
		
	END;
$$;



CREATE OR REPLACE PROCEDURE ECOMMERCE.CLIENTEeFavorita(O_Nif_CLIENTE NUMERIC(9,0), O_PRODUTO_ID NUMERIC)
LANGUAGE plpgsql
AS $$
	DECLARE
		FID NUMERIC := RAND()*1000;
	BEGIN
		INSERT INTO ECOMMERCE.FAVORITO(FAV_ID, USER_NIF, PRODUTO_ID)
		VALUES (FID, O_Nif_CLIENTE, O_PRODUTO_ID);
	END;
$$;



CREATE OR REPLACE PROCEDURE ECOMMERCE.NewCart(O_USER_NIF)
LANGUAGE plpgsql
AS $$
	DECLARE
		CART_ID NUMERIC:= RAND()*1000;
		Preco NUMERIC = 0.00
	BEGIN
		INSERT INTO ECOMMERCE.CARRINHO()
	END;
$$;



CREATE OR REPLACE PROCEDURE ECOMMERCE.CLIENTEADICIONA_PRODUTOCart(O_Nif_CLIENTE NUMERIC(9,0), O_PRODUTO_ID NUMERIC, O_CART_ID NUMERIC, O_QUANTIDADE NUMERIC)
LANGUAGE plpgsql
AS $$
	DECLARE
		--CARTID NUMERIC := RAND()*1000;
		CARTPRODUTOID NUMERIC := RAND()*1000;
	BEGIN
		INSERT INTO ECOMMERCE.CARRINHO_PRODUTO_VENDA_VENDA(ID_C_P, CART_ID, PRODUTO_ID, QUANTIDADE)
		VALUES (CARTPRODUTOID, O_CART_ID, O_PRODUTO_ID, O_QUANTIDADE);
	END;
$$;



-- GERAR UM CARRINHO VAZIO EX:QUANDO SE CRIA UM NOVO UTILIZADOR
-- FAZER UM UPDATE AUTOMÁTICO DO TOTAL DO CARRINHO

-- ADICIONAR VALORES INICIAIS
